# Generated by Django 2.0 on 2020-08-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LikeNumModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False, verbose_name='点赞状态')),
                ('like_date', models.DateTimeField(auto_now_add=True, verbose_name='点赞时间')),
            ],
            options={
                'verbose_name': '点赞',
                'verbose_name_plural': '点赞',
                'db_table': 'LikeNum',
            },
        ),
        migrations.CreateModel(
            name='PostCommentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=300, verbose_name='评论内容')),
                ('pub_time', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
            ],
            options={
                'verbose_name': '帖子评论记录',
                'verbose_name_plural': '帖子评论记录',
                'db_table': 'post_comments',
            },
        ),
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('desc', models.TextField(verbose_name='帖子内容')),
                ('img', models.ImageField(blank=True, null=True, upload_to='post/images/%y/%d/63ada32373e944e688cee8d081df6e70', verbose_name='帖子图片')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('like_num', models.IntegerField(default=0, verbose_name='点赞数')),
                ('visit', models.IntegerField(default=0, verbose_name='浏览量')),
            ],
            options={
                'verbose_name': '帖子',
                'verbose_name_plural': '帖子',
                'db_table': 'post',
            },
        ),
    ]
