# Generated by Django 2.0 on 2020-08-02 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confession', '0002_auto_20200802_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='post/images/%y/%d/918a97a71b4147efb591263d2ed109ab', verbose_name='帖子图片'),
        ),
    ]
