# Generated by Django 2.0 on 2020-08-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confession', '0003_auto_20200802_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='post/images/%y/%d/b2119dc43f9c437f94caa64843d94277', verbose_name='帖子图片'),
        ),
    ]
