# Generated by Django 2.0 on 2020-08-02 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchRecordsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(max_length=60, verbose_name='搜索关键词')),
                ('platform', models.CharField(max_length=60, verbose_name='平台')),
                ('times', models.IntegerField(default=0, verbose_name='搜索次数')),
            ],
            options={
                'verbose_name': '搜索记录',
                'verbose_name_plural': '搜索记录',
                'db_table': 'search_records',
            },
        ),
        migrations.CreateModel(
            name='UserSearchRecordsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_time', models.DateTimeField(auto_now_add=True, verbose_name='搜索时间')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record', to='search.SearchRecordsModel', verbose_name='搜索记录')),
            ],
            options={
                'verbose_name': '用户搜索记录',
                'verbose_name_plural': '用户搜索记录',
                'db_table': 'user_search_records',
            },
        ),
    ]
