# Generated by Django 2.0 on 2020-08-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotifyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='消息内容', verbose_name='消息内容')),
                ('notify_type', models.IntegerField(choices=[(0, '点赞'), (1, '评论'), (2, '活动参加'), (3, '跑腿接单')], default=0, help_text='消息类型', verbose_name='消息类型')),
                ('target_id', models.IntegerField(default=0, help_text='通过这个目标id和消息类型去找对应的记录', verbose_name='目标id')),
                ('sender_id', models.IntegerField(default=0, help_text='用户点赞评论等自动发送当前用户id', verbose_name='发送方用户id')),
                ('user_id', models.IntegerField(default=0, help_text='根据前端post的user_id来获取对应的消息列表', verbose_name='当前登录的用户id')),
                ('is_read', models.BooleanField(verbose_name='消息是否已读')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='消息创建时间')),
            ],
            options={
                'db_table': 'notify',
                'ordering': ['-created_at'],
            },
        ),
    ]
