# Generated by Django 2.0 on 2020-08-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_auto_20200802_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifymodel',
            name='sender_id',
            field=models.IntegerField(default=1, help_text='用户点赞评论等自动发送当前用户id', verbose_name='发送方用户id'),
        ),
        migrations.AlterField(
            model_name='notifymodel',
            name='target_id',
            field=models.IntegerField(default=1, help_text='通过这个目标id和消息类型去找对应的记录', null=True, verbose_name='目标id'),
        ),
        migrations.AlterField(
            model_name='notifymodel',
            name='user_id',
            field=models.IntegerField(default=1, help_text='根据前端post的user_id来获取对应的消息列表', verbose_name='当前登录的用户id'),
        ),
    ]
