# Generated by Django 2.0 on 2020-08-02 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fivetaskmodel',
            name='join_users',
            field=models.ManyToManyField(blank=True, related_name='join_users', to=settings.AUTH_USER_MODEL, verbose_name='报名用户'),
        ),
        migrations.AddField(
            model_name='fivetaskmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pubUser', to=settings.AUTH_USER_MODEL, verbose_name='发布人'),
        ),
    ]
