# Generated by Django 2.0 on 2020-08-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost', '0003_auto_20200802_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fivetaskmodel',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='lp/images/%y/%d/099899753d904a7192ace7b2e54dc05b', verbose_name='物品图片'),
        ),
    ]
